### ISSUE TITLE
Add methods for raising if there are incorrect field mappings

### ISSUE THREAD

**Issue by paulcsmith** [luckyframework/lucky_record#127]
Run `LuckyRecord::Model.ensure_correct_field_mappings!`

Raises if:

* There is a field defined in the model doesn't have a matching column on the table
* The table is missing
* The field is marked as nilable with `?` but the column on the table is NON NULL
* A field is marked as non-nilable (no `?`), but the column allows NULL

Ideally it should use https://crystal-lang.org/api/0.23.1/Levenshtein.html to check for similar named tables/field and suggest corrections. You can see how this is used for missing assets in Lucky: https://github.com/luckyframework/lucky/blob/e6c5efc578b9753816985db4fc44fae589b7573f/src/run_macros/missing_asset.cr#L10

It should also give helpful suggestions when it raises:

```
<FIELD NAME> is marked as nilable (nickname : String?), but the database column does not allow nils.

Try this...
   
  * Mark the field as non-nilable in your model: field nickname : String
  * Or, change the column in a migration to allow nils: make_optional :users, :nickname
```

It does *not* need to find and display all problems at once. So if there is a missing table *and* a model has a missing field, just display the error for a missing table. Then once the table is added and they run it again show the error for a missing field.

**Comment by paulcsmith** [comment]
It might be better to split these into separate PRs. e.g. one for checking for table names. One for checking if a field exists, and another for checking whether a field allow null or not

**Comment by paulcsmith** [comment]
@mikeeus I'm not sure if you have time, but if you're looking for something to work on for Lucky, this would be *really* awesome. Of course up to you though :)

**Comment by mikeeus** [comment]
Sure, this looks really interesting! I'll see what I can do
