### ISSUE TITLE
Chaining `count` to order clauses raises runtime sql error

### ISSUE THREAD

**Issue by hanneskaeufler** [luckyframework/lucky_record#129]
With a scope
```crystal
def latest
  created_at.desc_order
end
```

running
```crystal
MyQuery.new.latest.count
```

will show error like:
<img width="794" alt="bildschirmfoto 2017-12-01 um 23 41 41" src="https://user-images.githubusercontent.com/68024/33506972-6bbe7ce2-d6f2-11e7-8233-8912af8a48eb.png">

**Comment by hanneskaeufler** [comment]
```crystal
    it "can be chained to order clauses" do
      count = UserQuery.new.created_at.desc_order.count
    end
```

Will reproduce inside `query_spec.cr`

**Comment by paulcsmith** [comment]
I just tried this and can confirm that the generated SQL does not work with order clauses. Here is how Rails handles it:

With an order but no limit:
```
# It just omits the order because it is irrelevant to the results
[2] pry(main)> User.all.order(:id).count
   (14.5ms)  SELECT COUNT(*) FROM "users"
=> 2669
```

With an order, and limit
```
# It has to perform a subquery to get this working correctly
[4] pry(main)> User.all.order(:id).limit(3).count
   (0.5ms)  SELECT COUNT(*) FROM (SELECT  1 FROM "users" ORDER BY "users"."id" ASC LIMIT $1) subquery_for_count  [["LIMIT", 3]]
=> 3
```

I think the steps for fixing this would be:

1. Remove the all ordering if there is no limit/offset and trying to count
2. Raise if trying to use limit/offset with count (for now)

Later on:

1. Use subqueries to allow limit/offset and order with count

I think it would be rarer to use limit/offset with count, so it's better to at least raise and let people know that it is not yet supported. Then later on add the subquery to make it possible.
