### ISSUE TITLE
Setting a nilable field to nil through a form errors

### ISSUE THREAD

**Issue by hanneskaeufler** [luckyframework/lucky_record#177]
Say you have a model with a nilable date field

```crystal
class Post < BaseModel
  table :posts do
    field published_at : Time?
  end
end
```

And a form that allows setting the field to nil with a checkbox

```crystal
class PostForm < Post::BaseForm
  allow_virtual published : Bool

  def prepare
    published_at.value = published.value ? Time.now : nil
  end
end
```

Submitting the form with the checkbox unchecked (so setting the field to `nil`) will return the following error:

`ERROR: invalid input syntax for type timestamp with time zone: "" (PQ::PQError)`

**Comment by hanneskaeufler** [comment]
See #178 for my proposed fix, however I hope there's a better way other then to nil-check.

**Comment by paulcsmith** [comment]
@hanneskaeufler I made a PR similar to yours here: https://github.com/luckyframework/lucky_record/pull/180 and merged it in. Thanks for pointing this out! It worked ok with nil string fields by setting them to an empty string, but that of course is not desired, and it would cause failures on anything other than string columns. 

LMK if this latest version change fixes it :)

**Comment by hanneskaeufler** [comment]
Cool, thanks! Still haven't figured out how to pin lucky's transient dependencies to a specific version so will have to wait on a version bump in lucky_record and lucky to try this :)
