### ISSUE TITLE
Rename field -> column

### ISSUE THREAD

**Issue by paulcsmith** [luckyframework/lucky_record#186]
The macro is confusingly named because we also refer to "fields" as `LuckyRecord::Field` in a form. To avoid confusion, rename `field` -> `column`. This makes discussing things and writing about them a lot easier. It is slightly longer to type (1 character) but I don't think that'll matter. The additional clarity is important.

**Comment by hanneskaeufler** [comment]
Yeah, considering we are using the macro inside the `table: foo do` block, I would agree `column` is more fitting.
