### ISSUE TITLE
Merge LuckyMigrator into LuckyRecord. 

### ISSUE THREAD

**Issue by paulcsmith** [luckyframework/lucky_record#233]

**Comment by edwardloveall** [comment]
The way I'd think about this is: does the implementation of LuckyMigrator depend on LuckyRecord? If so, I think they should probably be merged.

**Comment by paulcsmith** [comment]
Let's move forward with this. The last few PRs to LuckyRecord/Migrator have required changes to both and it is a pain to orchestrate. I'll try to tackle this one of these days :)
