### ISSUE TITLE
lucky_cli & habitat as production dependency

### ISSUE THREAD

**Issue by jackturnbull** [luckyframework/lucky_record#278]
Won't overcomplicate the description, simply; are lucky_cli and habitat required as production level dependencies rather than development_dependencies? If so, why?

**Comment by fernandes** [comment]
hi @jackturnbull afaik habitat is used to configure the application, so is needed even in production, not sure about `lucky_cli`

**Comment by hanneskaeufler** [comment]
Hi, yes, both are non-dev dependencies. habitat to set configuration, and lucky_cli for the tasks, so you are able to run `lucky db.reset` (see https://github.com/luckyframework/lucky_record/blob/master/tasks.cr).

**Comment by paulcsmith** [comment]
Thanks for answering @fernandes and @hanneskaeufler 👍 I'll go ahead and close this now.

**Comment by jackturnbull** [comment]
Perfect thanks for clearing up @hanneskaeufler!
