### ISSUE TITLE
LuckyRecord fails to compile on cry0.26 - Time.parse signature change

### ISSUE THREAD

**Issue by robacarp** [luckyframework/lucky_record#279]
Starting from scratch, on a new project with Crystal master as of ea543f346, `lucky run` produces this error. The breaking change to Time.parse means that this should probably be `parse_utc`

```
instantiating 'Time::Lucky:Module#parse(String)'
in lib/lucky_record/src/lucky_record/charms/time_extensions.cr:11: wrong number of arguments for 'Time.parse' (given 2, expected 3)
Overloads are:
 - Time.parse(time : String, pattern : String, location : Location)

      SuccessfulCast(Time).new Time.parse(value, "%FT%X%z").to_utc
```

**Comment by paulcsmith** [comment]
>  For more context: https://gitter.im/luckyframework/Lobby?at=5b7c7af8ff445156161c130f

It looks like this has been fixed already in https://github.com/luckyframework/lucky_record/commit/332511b9cedad39e9f1ae5556d9f576d9d0dd794
