### ISSUE TITLE
Type restrictions on Form constructors to prevent opaque errors when initializing a form with the incorrect parameters

### ISSUE THREAD

**Issue by robacarp** [luckyframework/lucky_record#305]
I recently received the runtime stack trace:

```text
Nil assertion failed at src/forms/user/account_form.cr:1 (Exception)
  from /usr/local/Cellar/crystal/0.27.0/src/nil.cr:107:5 in 'not_nil!'
  from src/actions/my/update.cr:0:1 in 'call'
```

The problem turned out to be that I was calling `AccountForm.update(params)` instead of `AccountForm.update(model_object, params)`. It’s obviously my mistake, but the opaque compiler error made an adventure out of debugging it because the error was very distant from the code which triggered the runtime exception. 

[Adding a type restriction here](https://github.com/luckyframework/lucky_record/blob/9c4a1b75ccc7c1f7355eb0972083ea0c7ec642f3/src/lucky_record/needy_initializer_and_save_methods.cr#L112 ) would prevent this opaque error and force the compiler to provide a more helpful error message.

**Comment by paulcsmith** [comment]
Closed by #307
