### ISSUE TITLE
Add aggregate methods like count, average, min, max, sum

### ISSUE THREAD

**Issue by paulcsmith** [luckyframework/lucky_record#96]
`UserQuery.new.company.lower.is("thoughtbot").count # How many users work at thoughtbot? `

Holding off for now: https://github.com/luckyframework/record/issues/96#issuecomment-345522173

- [x] count #105
- [x] Change `count` to `select_count`
- [x] `select_average`
- [x] `select_min`
- [x] `select_max`
- [x] `select_sum`

**Comment by hanneskaeufler** [comment]
I did take a shot at `count` in #105.

**Comment by paulcsmith** [comment]
I was thinking about the other methods and I think it would be best to hold off on them for now. The reason is that I'd like to come up with something for querying by avg/min/max, etc. and for getting the number back. For example:

```crystal
CommentQuery.new.rating.avg.gte(4.0) # Gets comments with a good rating
CommentQuery.new.rating.get_avg # Gets the average rating
```

I'm not 100% sold on those method names though. Thoughts?

**Comment by hanneskaeufler** [comment]
Just to throw in two more
```crystal
CommentQuery.new.rating.calculate_avg # Gets the average rating
CommentQuery.new.rating.avg! # Gets the average rating
```

**Comment by paulcsmith** [comment]
I've been thinking about this and I think it should be `select_avg`, `select_count`, etc. because it matches SQL terminology.
