### ISSUE TITLE
Add class method shortcuts for find/first/last

### ISSUE THREAD

**Issue by paulcsmith** [luckyframework/lucky_record#97]
So you can do `UserQuery.find(id)`, `UserQuery.first/last`

**Comment by coderhs** [comment]
I would like to give this one a try.

**Comment by coderhs** [comment]
The file i need to add this method to is `query.cr` right? the same method as where the `destroy_all` method is present.

**Comment by paulcsmith** [comment]
@coderhs it would go in https://github.com/luckyframework/record/blob/master/src/lucky_record/queryable.cr

Thanks for taking this on. Lmk if you have any other questions :)

**Comment by paulcsmith** [comment]
@coderhs Just wondering if you still plan to take this one on. If not that is totally ok (I know things get busy), I'm just wondering so I can figure out if it is something I should do instead.

**Comment by coderhs** [comment]
@paulcsmith sorry for being MIA, I was hoping to finish this over a weekend, but then it got extended. I will be able to work on this weekend and have it finished. If it's urgent then I will leave it for others (Whoever is available) to pick it up.

Over the weekend I will pick up some other issue and help out there.

**Comment by paulcsmith** [comment]
@coderhs No problem at all. I just wanted to check in. It's not urgent so you can still pick it up this weekend. Thanks for helping out with Lucky :)

**Comment by jdbann** [comment]
Looks like this is done?

**Comment by paulcsmith** [comment]
@jdbann Not quite yet. There are instance methods, but no class methods: https://github.com/luckyframework/lucky_record/blob/236ee3c30ff7eb9079825c9ce283aae1c56aa92c/src/lucky_record/queryable.cr#L61

It's been a bit so I think someone else can tackle this (or I'll do it at some point if no one wants)

**Comment by jdbann** [comment]
I'll jump on it now
